// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-site-config.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_site_config_default = defineTool({
  name: "get_site_config",
  title: "Get MY LIBERAL PONY site config",
  description: "Return the current MY LIBERAL PONY site configuration: branding, spotlight release, videos, social links, press mentions, navigation and contact email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("mlp_site_config").select("*").limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { config: data }
    };
  }
});

// src/lib/mcp/tools/list-releases.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_releases_default = defineTool2({
  name: "list_releases",
  title: "List MY LIBERAL PONY releases",
  description: "List every MY LIBERAL PONY release stored in the site database, ordered by release date descending.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("releases").select("*").order("release_date", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { releases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-tagline.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var update_tagline_default = defineTool3({
  name: "update_tagline",
  title: "Update site tagline",
  description: "Update the site-wide tagline shown under the MY LIBERAL PONY heading. Requires an admin-authorized session; RLS enforces write permission.",
  inputSchema: { tagline: z.string().trim().min(1).max(200).describe("New tagline text.") },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ tagline }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: existing, error: readErr } = await supabase.from("mlp_site_config").select("id, branding").limit(1).maybeSingle();
    if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "No site config row exists." }], isError: true };
    const branding = { ...existing.branding, tagline };
    const { error } = await supabase.from("mlp_site_config").update({ branding }).eq("id", existing.id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Tagline updated to: ${tagline}` }],
      structuredContent: { tagline }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kamlnoppdrjwzasdoedf";
var mcp_default = defineMcp({
  name: "my-liberal-pony-mcp",
  title: "MY LIBERAL PONY",
  version: "0.1.0",
  instructions: "Tools for the MY LIBERAL PONY website. Read site configuration and releases, and (as an authorized admin) update the site tagline. Calls act as the signed-in Supabase user; write access is enforced by Row-Level Security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_site_config_default, list_releases_default, update_tagline_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
